app_name: DuckDuckGo Search
download_directory: C:\Users\sanal\Downloads\duckduckgo_images
log_level: INFO
max_results: 200
recent_directories: []
timeout: 30.0
version: 1.0.0
window_geometry:
  height: 800
  width: 1200
  x: 100
  y: 100
workers: 4
