ADSK_3DSMAX_X64_2022: C:\Program Files\Autodesk\3ds Max 2022\
ALLUSERSPROFILE: C:\ProgramData
ANS_OLD_ATTACH: '1'
APPDATA: C:\Users\User\AppData\Roaming
BUNDLED_DEBUGPY_PATH: c:\Users\User\.vscode\extensions\ms-python.debugpy-2025.10.0-win32-x64\bundled\libs\debugpy
CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_39204_KMYVCROZNHSYRQKU
CLINE_ACTIVE: 'true'
COLORTERM: truecolor
COMMONPROGRAMFILES: C:\Program Files\Common Files
COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432: C:\Program Files\Common Files
COMPUTERNAME: LAPTOP-IO31NATG
COMSPEC: C:\windows\system32\cmd.exe
CONCURRENT_TIMEOUT: 30.0
CONCURRENT_WORKERS: 4
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA_PATH_V12_1: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA_PATH_V12_4: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
DATASPELL: C:\Program Files\JetBrains\DataSpell 2023.1.1\bin;
DEFAULT_MAX_RESULTS: 200
DRIVERDATA: C:\Windows\System32\Drivers\DriverData
GIT_ASKPASS: c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
HOMEDRIVE: 'C:'
HOMEPATH: \Users\User
KEYSHOT_EXTERNAL_LICENSE_FOLDER: D:\Program Files\mc\
LANG: ru_RU.UTF-8
LOCALAPPDATA: C:\Users\User\AppData\Local
LOGONSERVER: \\LAPTOP-IO31NATG
LOG_LEVEL: INFO
NUMBER_OF_PROCESSORS: '12'
OCULUSBASE: C:\Program Files\Oculus\
ONEDRIVE: C:\Users\User\OneDrive
ONEDRIVECONSUMER: C:\Users\User\OneDrive
ONLINESERVICES: Online Services
ORIGINAL_XDG_CURRENT_DESKTOP: undefined
OS: Windows_NT
PATH: C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\PySide6;C:\Program
  Files\PowerShell\7;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Program
  Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;C:\Program Files\NVIDIA GPU
  Computing Toolkit\CUDA\v12.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\libnvvp;C:\Program
  Files (x86)\VMware\VMware Player\bin\;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program
  Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin;C:\Program
  Files\Oculus\Support\oculus-runtime;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program
  Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\Common Files\Autodesk
  Shared\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft
  SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program
  Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL
  Server\150\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance
  Toolkit\;C:\Program Files\Calibre2\;C:\Program Files\CMake\bin;C:\Program Files\PuTTY\;C:\Program
  Files\TortoiseGit\bin;C:\Program Files\Graphviz\bin;C:\Program Files\dotnet\;C:\Program
  Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
  Files\NVIDIA Corporation\Nsight Compute 2023.1.0\;C:\Program Files\NVIDIA Corporation\NVIDIA
  app\NvDLISR;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\nodejs\;C:\Program
  Files\PowerShell\7\;C:\Users\User\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\User\AppData\Local\Programs\Python\Python311\;C:\Users\User\.cargo\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Program
  Files\JetBrains\PyCharm Community Edition 2021.3.1\bin;C:\Users\User\AppData\Local\Programs\Microsoft
  VS Code\bin;C:\Users\User\AppData\Local\Programs\Python\Python310;C:\Program Files\JetBrains\DataSpell
  2023.1.1\bin;C:\Program Files\JetBrains\PyCharm 2023.1.1\bin;C:\Users\User\.dotnet\tools;C:\Users\User\.cache\lm-studio\bin;C:\Users\User\AppData\Roaming\npm;C:\Program
  Files\JetBrains\PyCharm 2025.2\bin;c:\Users\User\.vscode\extensions\ms-python.debugpy-2025.10.0-win32-x64\bundled\scripts\noConfigScripts;c:\Users\User\AppData\Roaming\Code\User\globalStorage\github.copilot-chat\debugCommand
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PLATFORMCODE: KV
POWERSHELL_DISTRIBUTION_CHANNEL: MSI:Windows 10 Home
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
PROCESSOR_LEVEL: '6'
PROCESSOR_REVISION: a502
PROGRAMDATA: C:\ProgramData
PROGRAMFILES: C:\Program Files
PROGRAMFILES(X86): C:\Program Files (x86)
PROGRAMW6432: C:\Program Files
PSMODULEPATH: C:\Users\User\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program
  files\powershell\7\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program
  Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\
PUBLIC: C:\Users\Public
PYCHARM: C:\Program Files\JetBrains\PyCharm 2025.2\bin
PYCHARM COMMUNITY EDITION: C:\Program Files\JetBrains\PyCharm Community Edition 2021.3.1\bin;
PYDEVD_DISABLE_FILE_VALIDATION: '1'
PYSIDE6_OPTION_PYTHON_ENUM: 'True'
PYTHONSTARTUP: c:\Users\User\AppData\Roaming\Code\User\workspaceStorage\8e1e4ca61eb80f411f868754ca95f061\ms-python.python\pythonrc.py
PYTHON_BASIC_REPL: '1'
REGIONCODE: EMEA
SESSIONNAME: Console
SYSTEMDRIVE: 'C:'
SYSTEMROOT: C:\windows
TEMP: C:\Users\User\AppData\Local\Temp
TERM_PROGRAM: vscode
TERM_PROGRAM_VERSION: 1.104.0
TMP: C:\Users\User\AppData\Local\Temp
USERDOMAIN: LAPTOP-IO31NATG
USERDOMAIN_ROAMINGPROFILE: LAPTOP-IO31NATG
USERNAME: User
USERPROFILE: C:\Users\User
VSCODE_DEBUGPY_ADAPTER_ENDPOINTS: c:\Users\User\.vscode\extensions\ms-python.debugpy-2025.10.0-win32-x64\.noConfigDebugAdapterEndpoints\endpoint-1470852f8e829588.txt
VSCODE_GIT_ASKPASS_EXTRA_ARGS: ''
VSCODE_GIT_ASKPASS_MAIN: c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js
VSCODE_GIT_ASKPASS_NODE: C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_IPC_HANDLE: \\.\pipe\vscode-git-1f0cfe41fe-sock
VSCODE_INJECTION: '1'
VSCODE_PYTHON_AUTOACTIVATE_GUARD: '1'
WINDIR: C:\windows
__PSLOCKDOWNPOLICY: '0'
